services:

  postgres:
    image: postgres:latest
    container_name: postgres_blog
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_blog:/var/lib/postgresql/data
    ports:
      - '${DB_PORT:-5432}:5432'

volumes:
  postgres_blog:
